services:
    pandelosplus:
        hostname: pandelosplus
        container_name: pandelosplus
        image: pandelosplus
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./input:/home/pdp/PanDelos-plus/input
            - ./output:/home/pdp/PanDelos-plus/output
