name: "Docker build image test"

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main

jobs:
    docker-test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Build Docker image
              run: docker build -t pdp:test .

            - name: Remove Docker image
              run: docker rmi pdp:test
